"use client";
import { useEffect, useState } from "react";
import StaffShell from "@/components/StaffShell";
import { staffFetch } from "@/lib/apiClient";
import UiIcon from "@/components/UiIcon";
import SecureImage from "@/components/SecureImage";

const tabs=[["personal","ข้อมูลส่วนตัว","person"],["position","ตำแหน่งและงาน","briefcase"],["education","การศึกษา","book"],["license","ใบอนุญาต","shield"],["history","ตำแหน่ง/วิทยฐานะ","chart"],["decorations","เครื่องราชฯ","star"],["training","การพัฒนาตนเอง","calendar"],["documents","เอกสาร","folder"]];
export default function PersonnelDetail({params}){
 const [id,setId]=useState(""),[p,setP]=useState(null),[tab,setTab]=useState("personal"),[edit,setEdit]=useState(false),[msg,setMsg]=useState(""),[uploading,setUploading]=useState(false);
 useEffect(()=>{Promise.resolve(params).then(v=>{setId(v.id);staffFetch(`/api/personnel/${v.id}`).then(d=>setP(d.personnel)).catch(e=>setMsg(e.message))})},[params]);
 async function save(){try{await staffFetch(`/api/personnel/${id}`,{method:"PATCH",body:JSON.stringify(p)});setMsg("บันทึกข้อมูลบุคลากรแล้ว");setEdit(false)}catch(e){setMsg(e.message)}}
 function set(k,v){setP({...p,[k]:v})}
 async function upload(file){if(!file)return;setUploading(true);setMsg("");try{const token=await (await import("@/lib/firebase")).auth.currentUser.getIdToken();const form=new FormData();form.append("file",file);form.append("kind","personnel_document");const r=await fetch("/api/files/upload",{method:"POST",headers:{Authorization:`Bearer ${token}`},body:form});const d=await r.json();if(!r.ok)throw new Error(d.error);setMsg("อัปโหลดเอกสารเข้า Google Drive แล้ว")}catch(e){setMsg(e.message||"อัปโหลดไม่สำเร็จ")}finally{setUploading(false)}}
 if(!p)return <StaffShell title="ข้อมูลบุคลากร"><div className="content-loader">กำลังโหลดข้อมูล...</div></StaffShell>;
 const name=`${p.prefix||""}${p.firstName||""} ${p.lastName||""}`.trim();
 return <StaffShell title="ข้อมูลบุคลากร">
  <div className="profile-breadcrumb"><a href="/staff/personnel">ข้อมูลบุคลากร</a><span>›</span><b>{name}</b></div>
  {msg&&<div className="toast-notice">{msg}<button onClick={()=>setMsg("")}>×</button></div>}
  <section className="personnel-profile-hero"><div className="personnel-photo">{p.photoDocumentId?<SecureImage documentId={p.photoDocumentId} alt="รูปบุคลากร"/>:p.firstName?.[0]}</div><div><small>PERSONNEL PROFILE</small><h1>{name}</h1><p>{p.position||"บุคลากร"}{p.academicRank?` • ${p.academicRank}`:""}</p><div className="profile-chip-row"><span className="chip blue">{p.subjectGroup||"ไม่ระบุกลุ่มสาระ"}</span><span className="chip green">{p.managementGroup||"ยังไม่กำหนดกลุ่มบริหาร"}</span></div></div><div className="profile-hero-actions"><button className="toolbar-btn soft" onClick={()=>setEdit(v=>!v)}><UiIcon name="edit" size={17}/>{edit?"ยกเลิก":"แก้ไขข้อมูล"}</button>{p.phone&&<a className="toolbar-btn green" href={`tel:${p.phone}`}><UiIcon name="phone" size={17}/>โทรศัพท์</a>}</div></section>
  <div className="profile-tabs scroll">{tabs.map(([k,l,icon])=><button key={k} className={tab===k?"active":""} onClick={()=>setTab(k)}><UiIcon name={icon} size={18}/>{l}</button>)}</div>
  <section className="profile-detail-card">
   {tab==="personal"&&<><Head icon="person" title="ข้อมูลส่วนตัว"/><div className="info-grid">{edit?<><Field label="คำนำหน้า" value={p.prefix} onChange={v=>set("prefix",v)}/><Field label="ชื่อ" value={p.firstName} onChange={v=>set("firstName",v)}/><Field label="นามสกุล" value={p.lastName} onChange={v=>set("lastName",v)}/><Field label="เลขประจำตัวประชาชน" value={p.citizenId} onChange={v=>set("citizenId",v)}/><Field label="เบอร์โทรศัพท์" value={p.phone} onChange={v=>set("phone",v)}/><Field label="อีเมล" value={p.email} onChange={v=>set("email",v)}/></>:<><Info label="เลขประจำตัวประชาชน" value={p.citizenId}/><Info label="วันเกิด" value={p.birthDateBE||p.birthDate}/><Info label="เพศ" value={p.gender}/><Info label="เบอร์โทรศัพท์" value={p.phone}/><Info label="อีเมล" value={p.email}/><Info label="ที่อยู่ปัจจุบัน" value={p.currentAddress}/></>}</div></>}
   {tab==="position"&&<><Head icon="briefcase" title="ตำแหน่งและการปฏิบัติงาน"/><div className="info-grid">{edit?<><Field label="ประเภทบุคลากร" value={p.personnelType} onChange={v=>set("personnelType",v)}/><Field label="ตำแหน่ง" value={p.position} onChange={v=>set("position",v)}/><Field label="วิทยฐานะ" value={p.academicRank} onChange={v=>set("academicRank",v)}/><Field label="เลขที่ตำแหน่ง" value={p.positionNumber} onChange={v=>set("positionNumber",v)}/><Field label="กลุ่มสาระ/ฝ่าย" value={p.subjectGroup} onChange={v=>set("subjectGroup",v)}/><Field label="กลุ่มบริหาร" value={p.managementGroup} onChange={v=>set("managementGroup",v)}/></>:<><Info label="ประเภทบุคลากร" value={p.personnelType}/><Info label="ตำแหน่ง" value={p.position}/><Info label="วิทยฐานะ" value={p.academicRank}/><Info label="เลขที่ตำแหน่ง" value={p.positionNumber}/><Info label="กลุ่มสาระ/ฝ่าย" value={p.subjectGroup}/><Info label="กลุ่มบริหาร" value={p.managementGroup}/><Info label="วิชาเอก" value={p.major}/><Info label="วันที่เริ่มงานที่โรงเรียน" value={p.schoolStartDate}/></>}</div></>}
   {tab==="education"&&<ListSection title="ประวัติการศึกษา" icon="book" items={p.education||[]} empty="ยังไม่มีประวัติการศึกษา" render={x=><><b>{x.level||x.degreeName||"วุฒิการศึกษา"}</b><span>{x.degreeName||""} {x.field?`• ${x.field}`:""}</span><small>{x.institution||""} {x.graduationYear?`• พ.ศ. ${x.graduationYear}`:""}</small></>}/>} 
   {tab==="license"&&<ListSection title="ใบอนุญาตประกอบวิชาชีพ" icon="shield" items={p.licenses||[]} empty="ยังไม่มีข้อมูลใบอนุญาต" render={x=><><b>{x.type||"ใบอนุญาต"}</b><span>เลขที่ {x.licenseNo||"—"}</span><small>หมดอายุ {x.expiryDate||"ไม่ระบุ"}</small></>}/>} 
   {tab==="history"&&<ListSection title="ประวัติตำแหน่งและวิทยฐานะ" icon="chart" items={p.positionHistory||[]} empty="ยังไม่มีประวัติตำแหน่ง" render={x=><><b>{x.position||"ตำแหน่ง"} {x.academicRank||""}</b><span>{x.school||x.unit||""}</span><small>{x.effectiveDate||x.year||""}</small></>}/>} 
   {tab==="decorations"&&<ListSection title="เครื่องราชอิสริยาภรณ์" icon="star" items={p.decorations||[]} empty="ยังไม่มีข้อมูลเครื่องราชอิสริยาภรณ์" render={x=><><b>{x.class||x.name||"รายการ"}</b><span>{x.fullName||x.abbreviation||""}</span><small>พ.ศ. {x.year||"—"}</small></>}/>} 
   {tab==="training"&&<ListSection title="การพัฒนาตนเอง / อบรม" icon="calendar" items={p.training||[]} empty="ยังไม่มีประวัติการอบรม" render={x=><><b>{x.course||"หลักสูตร"}</b><span>{x.organizer||""}</span><small>{x.hours?`${x.hours} ชั่วโมง`:""} {x.startDate?`• ${x.startDate}`:""}</small></>}/>} 
   {tab==="documents"&&<><Head icon="folder" title="เอกสารบุคลากร"/><div className="document-upload"><span><UiIcon name="upload" size={28}/></span><div><b>อัปโหลดเอกสารเข้า Google Drive</b><p>รองรับ PDF, JPG, PNG และไฟล์เอกสาร ขนาดไม่เกิน 8 MB</p></div><label className="toolbar-btn blue">{uploading?"กำลังอัปโหลด...":"เลือกไฟล์"}<input type="file" hidden disabled={uploading} onChange={e=>upload(e.target.files?.[0])}/></label></div><div className="document-types">{["สำเนาบัตรประชาชน","ทะเบียนบ้าน","วุฒิการศึกษา","Transcript","ใบอนุญาตประกอบวิชาชีพ","คำสั่งแต่งตั้ง/ย้าย","คำสั่งวิทยฐานะ","เครื่องราชฯ","อื่นๆ"].map(x=><span key={x}><UiIcon name="file" size={16}/>{x}</span>)}</div></>}
   {edit&&["personal","position"].includes(tab)&&<div className="profile-save-row"><button className="soft-secondary" onClick={()=>setEdit(false)}>ยกเลิก</button><button className="soft-primary" onClick={save}><UiIcon name="check" size={17}/>บันทึกการแก้ไข</button></div>}
  </section>
 </StaffShell>
}
function Head({icon,title}){return <div className="section-head-line"><span><UiIcon name={icon}/></span><div><small>PERSONNEL INFORMATION</small><h2>{title}</h2></div></div>}
function Info({label,value}){return <div className="info-item"><span>{label}</span><b>{value||"—"}</b></div>}
function Field({label,value,onChange}){return <label className="modern-field"><span>{label}</span><input value={value||""} onChange={e=>onChange(e.target.value)}/></label>}
function ListSection({title,icon,items,empty,render}){return <><Head icon={icon} title={title}/><div className="timeline-list">{items.length?items.map((x,i)=><article key={i}><i/ ><div>{render(x)}</div></article>):<div className="empty-state small"><UiIcon name={icon} size={34}/><b>{empty}</b><span>ข้อมูลส่วนนี้สามารถเพิ่มได้โดยงานบุคคลหรือผู้ดูแลระบบ</span></div>}</div></>}
