"use client";
import { useEffect, useMemo, useState } from "react";
import StaffShell from "@/components/StaffShell";
import { staffFetch } from "@/lib/apiClient";
import UiIcon from "@/components/UiIcon";
import SecureImage from "@/components/SecureImage";

export default function StudentsPage(){
  const [rows,setRows]=useState([]),[q,setQ]=useState(""),[grade,setGrade]=useState(""),[room,setRoom]=useState(""),[status,setStatus]=useState(""),[loading,setLoading]=useState(true);
  async function load(){setLoading(true);try{const d=await staffFetch(`/api/students?q=${encodeURIComponent(q)}&grade=${grade}&room=${room}&status=${status}`);setRows(d.students||[])}finally{setLoading(false)}}
  useEffect(()=>{load()},[]);
  const total=rows.length,complete=rows.filter(x=>x.profileStatus==="complete").length;
  return <StaffShell title="นักเรียนทั้งหมด">
    <div className="page-title-row"><div><small>STUDENT DIRECTORY</small><h1>ข้อมูลนักเรียน</h1><p>ค้นหา ดูข้อมูล และติดตามความครบถ้วนของนักเรียนทั้งโรงเรียน</p></div><div className="page-title-badge"><UiIcon name="students"/>ข้อมูลนักเรียน</div></div>
    <section className="staff-stat-grid compact"><Stat icon="students" label="ผลการค้นหา" value={total} sub="คน" color="blue"/><Stat icon="check" label="ข้อมูลครบ" value={complete} sub="คน" color="green"/><Stat icon="clock" label="ยังไม่ครบ" value={total-complete} sub="คน" color="orange"/><Stat icon="search" label="ค้นหาทั้งโรงเรียน" value="พร้อม" sub="ชื่อ / รหัส / ชื่อเล่น" color="purple"/></section>
    <section className="room-toolbar"><div className="table-search grow"><UiIcon name="search" size={18}/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()} placeholder="ค้นหาด้วยรหัส ชื่อ นามสกุล หรือชื่อเล่น..."/></div><select value={grade} onChange={e=>setGrade(e.target.value)}><option value="">ทุกระดับชั้น</option>{[1,2,3,4,5,6].map(x=><option key={x} value={x}>ม.{x}</option>)}</select><input className="room-input" value={room} onChange={e=>setRoom(e.target.value)} placeholder="ห้อง"/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">ทุกสถานะ</option><option value="complete">ครบถ้วน</option><option value="incomplete">ยังไม่ครบ</option><option value="not_started">ยังไม่เริ่ม</option></select><button className="toolbar-btn blue" onClick={load}><UiIcon name="search" size={17}/>ค้นหา</button></section>
    <section className="data-card"><div className="data-card-head"><div><small>ALL STUDENTS</small><h2>รายชื่อนักเรียน</h2></div><span>{loading?"กำลังโหลด...":`${rows.length} รายการ`}</span></div><div className="responsive-table-wrap"><table className="pretty-table"><thead><tr><th>รูป</th><th>รหัสนักเรียน</th><th>ชื่อ-สกุล</th><th>ชั้น/ห้อง</th><th>เลขที่</th><th>สถานะ</th><th>โทรศัพท์</th><th>การดำเนินการ</th></tr></thead><tbody>{rows.map(s=>{const e=s.currentEnrollment||{};return <tr key={s.studentId}><td data-label="รูป"><div className="table-avatar">{s.photoDocumentId?<SecureImage documentId={s.photoDocumentId} alt="รูปนักเรียน"/>:s.firstName?.[0]}</div></td><td data-label="รหัส">{s.studentId}</td><td data-label="ชื่อ"><b>{s.prefix}{s.firstName} {s.lastName}</b><small>{s.nickname?`(${s.nickname})`:""}</small></td><td data-label="ชั้น">ม.{e.grade||"-"}/{e.room||"-"}</td><td data-label="เลขที่">{e.number??"-"}</td><td data-label="สถานะ"><StatusPill status={s.profileStatus}/></td><td data-label="โทรศัพท์">{s.phone||s.emergency?.primary?.phone||"—"}</td><td data-label="การดำเนินการ"><div className="table-actions"><a href={`/staff/students/${s.studentId}`}><UiIcon name="eye" size={16}/><span>ดูข้อมูล</span></a></div></td></tr>})}</tbody></table></div>{!loading&&!rows.length&&<div className="empty-state"><UiIcon name="search" size={38}/><b>ไม่พบข้อมูลนักเรียน</b><span>ลองเปลี่ยนคำค้นหาหรือตัวกรอง</span></div>}</section>
  </StaffShell>
}
function Stat({icon,label,value,sub,color}){return <article className={`staff-stat-card ${color}`}><span className="stat-icon"><UiIcon name={icon} size={24}/></span><div><small>{label}</small><b>{value}</b><em>{sub}</em></div></article>}
function StatusPill({status}){const s=status||"not_started";return <span className={`status-pill ${s}`}>{s==="complete"?"ครบถ้วน":s==="incomplete"?"รออัปเดต":"ยังไม่เริ่ม"}</span>}
