"use client";
import { useEffect, useMemo, useState } from "react";
import StaffShell from "@/components/StaffShell";
import { staffFetch } from "@/lib/apiClient";
import UiIcon from "@/components/UiIcon";
import SecureImage from "@/components/SecureImage";

const groups=["กลุ่มบริหารวิชาการ","กลุ่มบริหารงานบุคคล","กลุ่มบริหารงานทั่วไป","กลุ่มบริหารงานงบประมาณและอำนวยการ","กลุ่มบริหารงานกิจการนักเรียน"];
export default function PersonnelPage(){
 const [hrMode,setHrMode]=useState(false);
 const [rows,setRows]=useState([]),[q,setQ]=useState(""),[group,setGroup]=useState(""),[status,setStatus]=useState(""),[loading,setLoading]=useState(true),[showNew,setShowNew]=useState(false),[newP,setNewP]=useState({prefix:"",firstName:"",lastName:"",position:"ครู",academicRank:"",subjectGroup:"",managementGroup:"",status:"active"}),[msg,setMsg]=useState("");
 async function load(){setLoading(true);try{const d=await staffFetch(`/api/personnel?q=${encodeURIComponent(q)}`);setRows(d.personnel||[])}finally{setLoading(false)}}
 async function createPersonnel(){setMsg("");try{await staffFetch("/api/personnel",{method:"POST",body:JSON.stringify(newP)});setMsg("เพิ่มข้อมูลบุคลากรแล้ว");setShowNew(false);setNewP({prefix:"",firstName:"",lastName:"",position:"ครู",academicRank:"",subjectGroup:"",managementGroup:"",status:"active"});await load()}catch(e){setMsg(e.message)}}
 useEffect(()=>{setHrMode(new URLSearchParams(location.search).get("mode")==="hr");load()},[]);
 const filtered=useMemo(()=>rows.filter(x=>(!group||x.managementGroup===group)&&(!status||x.status===status)),[rows,group,status]);
 const active=rows.filter(x=>x.status==="active").length;
 const expiring=rows.filter(x=>x.licenseStatus==="expiring").length;
 return <StaffShell title={hrMode?"งานบุคคล":"ข้อมูลบุคลากร"}>
  <div className="page-title-row"><div><small>{hrMode?"HUMAN RESOURCES":"PERSONNEL DIRECTORY"}</small><h1>{hrMode?"งานบุคคล":"ข้อมูลครูและบุคลากร"}</h1><p>{hrMode?"ติดตามความครบถ้วน ใบอนุญาต การเกษียณ และเอกสารบุคลากร":"ข้อมูลส่วนตัว ตำแหน่ง ประวัติการศึกษา ใบอนุญาต และเอกสารสำคัญ"}</p></div><button className="toolbar-btn blue" onClick={()=>setShowNew(v=>!v)}><UiIcon name="plus" size={17}/>เพิ่มบุคลากร</button></div>
  {msg&&<div className="toast-notice">{msg}<button onClick={()=>setMsg("")}>×</button></div>}
  {showNew&&<section className="dashboard-panel new-personnel-card"><div className="panel-heading"><div><small>NEW PERSONNEL</small><h2>เพิ่มข้อมูลบุคลากร</h2></div><button className="text-button" onClick={()=>setShowNew(false)}>ปิด</button></div><div className="form-grid modern"><MiniField label="คำนำหน้า" value={newP.prefix} onChange={v=>setNewP({...newP,prefix:v})}/><MiniField label="ชื่อ" value={newP.firstName} onChange={v=>setNewP({...newP,firstName:v})}/><MiniField label="นามสกุล" value={newP.lastName} onChange={v=>setNewP({...newP,lastName:v})}/><MiniField label="ตำแหน่ง" value={newP.position} onChange={v=>setNewP({...newP,position:v})}/><MiniField label="วิทยฐานะ" value={newP.academicRank} onChange={v=>setNewP({...newP,academicRank:v})}/><MiniField label="กลุ่มสาระ/ฝ่าย" value={newP.subjectGroup} onChange={v=>setNewP({...newP,subjectGroup:v})}/><label className="modern-field"><span>กลุ่มบริหาร</span><select value={newP.managementGroup} onChange={e=>setNewP({...newP,managementGroup:e.target.value})}><option value="">เลือกกลุ่มบริหาร</option>{groups.map(g=><option key={g}>{g}</option>)}</select></label></div><div className="profile-save-row"><button className="soft-secondary" onClick={()=>setShowNew(false)}>ยกเลิก</button><button className="soft-primary" onClick={createPersonnel}><UiIcon name="check" size={17}/>บันทึกบุคลากร</button></div></section>}
  {hrMode&&<section className="hr-alert-strip"><article><UiIcon name="clock"/><div><b>ใบอนุญาตใกล้หมดอายุ</b><span>{expiring} รายการที่ควรตรวจสอบ</span></div></article><article><UiIcon name="calendar"/><div><b>การเกษียณอายุ</b><span>ติดตามข้อมูลปีเกษียณจากโปรไฟล์บุคลากร</span></div></article><article><UiIcon name="file"/><div><b>เอกสารบุคลากร</b><span>จัดเก็บใน Google Drive แบบ Private</span></div></article></section>}
  <section className="staff-stat-grid compact"><Stat icon="personnel" label="บุคลากรทั้งหมด" value={rows.length} sub="คน" color="blue"/><Stat icon="check" label="ปฏิบัติงาน" value={active} sub="คน" color="green"/><Stat icon="clock" label="ใบอนุญาตใกล้หมด" value={expiring} sub="รายการ" color="orange"/><Stat icon="briefcase" label="กลุ่มบริหาร" value="5" sub="กลุ่ม" color="purple"/></section>
  <section className="management-group-grid">{groups.map((g,i)=><button key={g} className={group===g?"active":""} onClick={()=>setGroup(group===g?"":g)}><span>{i+1}</span><b>{g}</b><small>{rows.filter(x=>x.managementGroup===g).length} คน</small></button>)}</section>
  <section className="room-toolbar"><div className="table-search grow"><UiIcon name="search" size={18}/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()} placeholder="ค้นหาชื่อ นามสกุล ตำแหน่ง หรือกลุ่มบริหาร..."/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">ทุกสถานะ</option><option value="active">ปฏิบัติงาน</option><option value="transferred">ย้าย</option><option value="retired">เกษียณ</option><option value="resigned">ลาออก</option></select><button className="toolbar-btn blue" onClick={load}><UiIcon name="search" size={17}/>ค้นหา</button><button className="toolbar-btn soft"><UiIcon name="download" size={17}/>ส่งออก Excel</button></section>
  <section className="data-card"><div className="data-card-head"><div><small>PERSONNEL</small><h2>รายชื่อบุคลากร</h2></div><span>{loading?"กำลังโหลด...":`${filtered.length} รายการ`}</span></div><div className="responsive-table-wrap"><table className="pretty-table"><thead><tr><th>รูป</th><th>ชื่อ-นามสกุล</th><th>ตำแหน่ง</th><th>วิทยฐานะ</th><th>กลุ่มสาระ/ฝ่าย</th><th>กลุ่มบริหาร</th><th>สถานะ</th><th>การดำเนินการ</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td data-label="รูป"><div className="table-avatar staff">{p.photoDocumentId?<SecureImage documentId={p.photoDocumentId} alt="รูปบุคลากร"/>:p.firstName?.[0]}</div></td><td data-label="ชื่อ"><b>{p.prefix}{p.firstName} {p.lastName}</b><small>{p.phone||p.email||""}</small></td><td data-label="ตำแหน่ง">{p.position||"—"}</td><td data-label="วิทยฐานะ">{p.academicRank||"—"}</td><td data-label="กลุ่มสาระ">{p.subjectGroup||p.department||"—"}</td><td data-label="กลุ่มบริหาร">{p.managementGroup||"—"}</td><td data-label="สถานะ"><span className={`status-pill ${p.status==="active"?"complete":"incomplete"}`}>{p.status==="active"?"ปฏิบัติงาน":p.status||"ไม่ระบุ"}</span></td><td data-label="การดำเนินการ"><div className="table-actions"><a href={`/staff/personnel/${p.id}`}><UiIcon name="eye" size={16}/><span>ดูข้อมูล</span></a></div></td></tr>)}</tbody></table></div>{!loading&&!filtered.length&&<div className="empty-state"><UiIcon name="personnel" size={38}/><b>ยังไม่มีข้อมูลบุคลากรตามเงื่อนไข</b><span>ปรับตัวกรองหรือเพิ่มบุคลากรในระบบ</span></div>}</section>
 </StaffShell>
}
function MiniField({label,value,onChange}){return <label className="modern-field"><span>{label}</span><input value={value||""} onChange={e=>onChange(e.target.value)}/></label>}
function Stat({icon,label,value,sub,color}){return <article className={`staff-stat-card ${color}`}><span className="stat-icon"><UiIcon name={icon} size={24}/></span><div><small>{label}</small><b>{value}</b><em>{sub}</em></div></article>}
