"use client";
import { useEffect, useMemo, useState } from "react";
import * as XLSX from "xlsx";
import StaffShell from "@/components/StaffShell";
import { staffFetch } from "@/lib/apiClient";
import UiIcon from "@/components/UiIcon";

const roleOptions=[["teacher","ครู"],["hr","งานบุคคล"],["admin","ผู้ดูแลระบบ"]];
export default function AdminPage(){
 const [tab,setTab]=useState("overview"),[msg,setMsg]=useState(""),[users,setUsers]=useState([]),[rooms,setRooms]=useState([]),[rows,setRows]=useState([]),[rollRows,setRollRows]=useState([]),[preview,setPreview]=useState(null),[account,setAccount]=useState({username:"",password:"",displayName:"",roles:["teacher"],homerooms:[]}),[room,setRoom]=useState({grade:"",room:"",academicYear:"2569"}),[busy,setBusy]=useState(false);
 async function refresh(){try{const[u,r]=await Promise.all([staffFetch("/api/admin/users"),staffFetch("/api/admin/classrooms")]);setUsers(u.users||[]);setRooms(r.classrooms||[])}catch(e){setMsg(e.message)}}
 useEffect(()=>{refresh()},[]);
 function readFile(file,cb){if(!file)return;const reader=new FileReader();reader.onload=e=>{const wb=XLSX.read(e.target.result,{type:"array"}),ws=wb.Sheets[wb.SheetNames[0]],data=XLSX.utils.sheet_to_json(ws,{defval:""});cb(data)};reader.readAsArrayBuffer(file)}
 async function importStudents(){setBusy(true);setMsg("");try{const d=await staffFetch("/api/admin/import-students",{method:"POST",body:JSON.stringify({rows})});setMsg(`นำเข้านักเรียนสำเร็จ ${d.count} คน`);setRows([])}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 async function createUser(){setBusy(true);setMsg("");try{await staffFetch("/api/admin/users",{method:"POST",body:JSON.stringify(account)});setMsg("สร้างบัญชีผู้ใช้งานแล้ว");setAccount({username:"",password:"",displayName:"",roles:["teacher"],homerooms:[]});await refresh()}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 async function createRoom(){setBusy(true);try{await staffFetch("/api/admin/classrooms",{method:"POST",body:JSON.stringify(room)});setMsg("เพิ่มห้องเรียนแล้ว");setRoom({...room,grade:"",room:""});await refresh()}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 async function rollover(mode){setBusy(true);try{const d=await staffFetch("/api/admin/rollover",{method:"POST",body:JSON.stringify({mode,rows:rollRows})});setPreview(d.preview);setMsg(mode==="commit"?"ขึ้นปีการศึกษาใหม่เรียบร้อย":"สร้าง Preview ผลกระทบแล้ว")}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 function toggleRole(role){setAccount(a=>({...a,roles:a.roles.includes(role)?a.roles.filter(x=>x!==role):[...a.roles,role]}))}
 function toggleHomeroom(r){const h={academicYear:String(r.academicYear),grade:String(r.grade),room:String(r.room)};const key=`${h.academicYear}_${h.grade}_${h.room}`;setAccount(a=>{const keys=a.homerooms.map(x=>`${x.academicYear}_${x.grade}_${x.room}`);return {...a,homerooms:keys.includes(key)?a.homerooms.filter(x=>`${x.academicYear}_${x.grade}_${x.room}`!==key):[...a.homerooms,h]}})}
 const activeUsers=users.filter(x=>x.status!=="inactive").length;
 return <StaffShell title="จัดการระบบ">
   <div className="page-title-row"><div><small>ADMINISTRATION</small><h1>จัดการระบบ</h1><p>บัญชีผู้ใช้งาน ห้องเรียน ข้อมูลนำเข้า ปีการศึกษา และการเชื่อมต่อระบบ</p></div><span className="page-title-badge"><UiIcon name="shield"/>Admin only</span></div>
   {msg&&<div className="toast-notice">{msg}<button onClick={()=>setMsg("")}>×</button></div>}
   <div className="admin-modern-tabs">{[["overview","ภาพรวม","home"],["import","นำเข้า Excel","upload"],["accounts","บัญชีผู้ใช้","users"],["rooms","ห้องเรียน","room"],["year","ปีการศึกษา","calendar"],["integration","การเชื่อมต่อ","cloud"]].map(([k,l,i])=><button key={k} className={tab===k?"active":""} onClick={()=>setTab(k)}><UiIcon name={i} size={18}/>{l}</button>)}</div>

   {tab==="overview"&&<><section className="staff-stat-grid compact"><Stat icon="users" label="บัญชีในระบบ" value={users.length} sub={`${activeUsers} บัญชีใช้งาน`} color="blue"/><Stat icon="room" label="ห้องเรียน" value={rooms.length} sub="ห้อง" color="green"/><Stat icon="calendar" label="ปีการศึกษา" value="2569" sub="ปีปัจจุบัน" color="orange"/><Stat icon="cloud" label="Cloud Services" value="3" sub="Firebase • Drive • Vercel" color="purple"/></section><section className="dashboard-grid-2"><article className="dashboard-panel"><div className="panel-heading"><div><small>SETUP CHECKLIST</small><h2>รายการตรวจสอบก่อนเปิดใช้จริง</h2></div></div><Checklist done label="Firebase Project" sub="banhaed-school-system-43dc6"/><Checklist done label="Firestore Database" sub="ฐานข้อมูลหลัก"/><Checklist done label="Email/Password Authentication" sub="สำหรับครูและบุคลากร"/><Checklist label="Firebase Admin Environment" sub="ใส่ FIREBASE_CLIENT_EMAIL และ FIREBASE_PRIVATE_KEY ใน Vercel"/><Checklist label="Google Drive Folder" sub="สร้างโฟลเดอร์หลักและกำหนด GOOGLE_DRIVE_FOLDER_ID"/></article><article className="dashboard-panel"><div className="panel-heading"><div><small>SECURITY</small><h2>แนวทางความปลอดภัย</h2></div></div><div className="security-notes"><p><UiIcon name="shield"/>ข้อมูลนักเรียนไม่เปิดอ่านจาก Firestore โดยตรง แต่ผ่าน Server API</p><p><UiIcon name="shield"/>สิทธิ์ครู / HR / Admin แยกจากการเป็นครูที่ปรึกษา</p><p><UiIcon name="shield"/>เอกสารส่วนบุคคลเก็บใน Google Drive แบบ Private</p><p><UiIcon name="shield"/>ก่อนขึ้นปีการศึกษาใหม่มี Preview ผลกระทบ</p></div></article></section></>}

   {tab==="import"&&<section className="dashboard-grid-2 align-start"><article className="dashboard-panel"><div className="panel-heading"><div><small>STUDENT IMPORT</small><h2>นำเข้านักเรียนจาก Excel</h2></div></div><div className="excel-columns"><b>คอลัมน์ขั้นต่ำ</b><span>รหัสนักเรียน</span><span>คำนำหน้า</span><span>ชื่อ</span><span>นามสกุล</span><span>ชั้น</span><span>ห้อง</span><span>เลขที่</span></div><label className="pretty-file-drop"><UiIcon name="upload" size={32}/><b>เลือกไฟล์ Excel</b><span>.xlsx หรือ .xls • ระบบจะอ่านข้อมูลก่อนนำเข้า</span><input type="file" accept=".xlsx,.xls" onChange={e=>readFile(e.target.files?.[0],setRows)}/></label><div className="import-result"><span>จำนวนแถวที่อ่านได้</span><b>{rows.length}</b><em>รายการ</em></div><button className="soft-primary full" disabled={!rows.length||busy} onClick={importStudents}>{busy?"กำลังนำเข้า...":"นำเข้าข้อมูลนักเรียน"}<UiIcon name="arrow"/></button></article><article className="dashboard-panel"><div className="panel-heading"><div><small>PREVIEW</small><h2>ตัวอย่างข้อมูล</h2></div></div><div className="mini-preview-table">{rows.slice(0,8).map((r,i)=><div key={i}><span>{r["รหัสนักเรียน"]||r.studentId||"—"}</span><b>{r["ชื่อ"]||r.firstName||""} {r["นามสกุล"]||r.lastName||""}</b><em>ม.{String(r["ชั้น"]||r.grade||"").replace(/^ม\.?/,"")}/{r["ห้อง"]||r.room||"-"}</em></div>)}</div>{!rows.length&&<div className="empty-state small"><UiIcon name="file" size={34}/><b>ยังไม่ได้เลือกไฟล์</b><span>เมื่อเลือก Excel ระบบจะแสดงตัวอย่างข้อมูลตรงนี้</span></div>}</article></section>}

   {tab==="accounts"&&<section className="dashboard-grid-2 align-start"><article className="dashboard-panel"><div className="panel-heading"><div><small>NEW ACCOUNT</small><h2>สร้างบัญชีครู/บุคลากร</h2></div></div><div className="stack-form modern"><Field label="ชื่อที่แสดง" value={account.displayName} onChange={v=>setAccount({...account,displayName:v})}/><Field label="Username" value={account.username} onChange={v=>setAccount({...account,username:v})}/><Field label="Password เริ่มต้น" value={account.password} type="password" onChange={v=>setAccount({...account,password:v})}/><div className="admin-role-picker"><span>บทบาท</span>{roleOptions.map(([r,l])=><label key={r} className={account.roles.includes(r)?"active":""}><input type="checkbox" checked={account.roles.includes(r)} onChange={()=>toggleRole(r)}/>{l}<small>{r}</small></label>)}</div><div className="homeroom-picker"><span>ห้องที่เป็นครูที่ปรึกษา (เลือกได้หลายห้อง)</span><div>{rooms.map(r=>{const key=`${r.academicYear}_${r.grade}_${r.room}`,checked=account.homerooms.some(x=>`${x.academicYear}_${x.grade}_${x.room}`===key);return <label key={r.id} className={checked?"active":""}><input type="checkbox" checked={checked} onChange={()=>toggleHomeroom(r)}/>ม.{r.grade}/{r.room}</label>})}</div></div><button className="soft-primary full" disabled={busy} onClick={createUser}><UiIcon name="plus"/>สร้างบัญชี</button></div></article><article className="dashboard-panel"><div className="panel-heading"><div><small>USERS</small><h2>บัญชีในระบบ</h2></div><span>{users.length} บัญชี</span></div><div className="account-list">{users.map(u=><div key={u.uid}><span className="account-avatar">{u.displayName?.[0]||"ค"}</span><div><b>{u.displayName||u.username}</b><small>@{u.username} • {(u.roles||[]).join(" / ")}</small></div><em>{u.status==="inactive"?"ปิดใช้งาน":"ใช้งาน"}</em></div>)}</div></article></section>}

   {tab==="rooms"&&<section className="dashboard-grid-2 align-start"><article className="dashboard-panel"><div className="panel-heading"><div><small>CLASSROOM</small><h2>เพิ่มห้องเรียน</h2></div></div><div className="stack-form modern"><Field label="ปีการศึกษา" value={room.academicYear} onChange={v=>setRoom({...room,academicYear:v})}/><Field label="ระดับชั้น" value={room.grade} placeholder="เช่น 1" onChange={v=>setRoom({...room,grade:v})}/><Field label="ห้อง" value={room.room} placeholder="เช่น 2" onChange={v=>setRoom({...room,room:v})}/><button className="soft-primary full" disabled={busy} onClick={createRoom}><UiIcon name="plus"/>เพิ่มห้องเรียน</button></div></article><article className="dashboard-panel"><div className="panel-heading"><div><small>CLASSROOM LIST</small><h2>ห้องเรียนในระบบ</h2></div><span>{rooms.length} ห้อง</span></div><div className="classroom-grid">{rooms.map(r=><div key={r.id}><span><UiIcon name="room"/></span><b>ม.{r.grade}/{r.room}</b><small>ปีการศึกษา {r.academicYear}</small></div>)}</div></article></section>}

   {tab==="year"&&<section className="dashboard-grid-2 align-start"><article className="dashboard-panel"><div className="panel-heading"><div><small>ACADEMIC YEAR</small><h2>ขึ้นปีการศึกษาใหม่</h2></div></div><div className="year-warning"><UiIcon name="shield"/><div><b>ระบบจะ Preview ก่อน Commit</b><span>นักเรียนที่ไม่พบในไฟล์ใหม่จะไม่ถูกเปลี่ยนสถานะให้อัตโนมัติ ยกเว้น ม.6 ที่จบการศึกษา</span></div></div><label className="pretty-file-drop"><UiIcon name="calendar" size={32}/><b>เลือก Excel ปีการศึกษาใหม่</b><span>ใช้รหัสนักเรียนเดิมเพื่อเชื่อมประวัติต่อเนื่อง</span><input type="file" accept=".xlsx,.xls" onChange={e=>readFile(e.target.files?.[0],setRollRows)}/></label><div className="button-row"><button className="soft-secondary" disabled={!rollRows.length||busy} onClick={()=>rollover("preview")}>Preview ผลกระทบ</button>{preview&&<button className="danger-modern" disabled={busy} onClick={()=>confirm("ยืนยันขึ้นปีการศึกษาใหม่? กรุณาตรวจสอบ Preview ก่อน")&&rollover("commit")}>ยืนยันขึ้นปีการศึกษา</button>}</div></article><article className="dashboard-panel"><div className="panel-heading"><div><small>IMPACT PREVIEW</small><h2>ผลกระทบโดยสรุป</h2></div></div>{preview?<div className="impact-grid"><Impact label="ปีเดิม" value={preview.fromYear}/><Impact label="ปีใหม่" value={preview.toYear}/><Impact label="นักเรียนปัจจุบัน" value={preview.current}/><Impact label="พบในไฟล์ใหม่" value={preview.found}/><Impact label="ม.6 ที่จบ" value={preview.graduates?.length||0}/><Impact label="ไม่พบในไฟล์ใหม่" value={preview.missing?.length||0} warn/></div>:<div className="empty-state small"><UiIcon name="calendar" size={34}/><b>ยังไม่มี Preview</b><span>เลือก Excel แล้วกด Preview ผลกระทบก่อน</span></div>}</article></section>}

   {tab==="integration"&&<section className="dashboard-grid-2 align-start"><article className="dashboard-panel"><div className="panel-heading"><div><small>CLOUD SERVICES</small><h2>Firebase</h2></div><span className="connected-pill">● เชื่อม Web SDK แล้ว</span></div><div className="integration-list"><p><b>Project ID</b><span>banhaed-school-system-43dc6</span></p><p><b>Authentication</b><span>Email / Password</span></p><p><b>Database</b><span>Cloud Firestore</span></p><p><b>Server Admin</b><span>ตั้งค่า Secret ใน Vercel</span></p></div></article><article className="dashboard-panel"><div className="panel-heading"><div><small>FILE STORAGE</small><h2>Google Drive</h2></div></div><div className="drive-setup-card"><span><UiIcon name="folder" size={34}/></span><div><b>เก็บรูปและเอกสาร</b><p>กำหนด GOOGLE_DRIVE_FOLDER_ID และแชร์โฟลเดอร์ให้ Firebase Service Account เป็น Editor</p></div></div><div className="env-list"><code>FIREBASE_CLIENT_EMAIL</code><code>FIREBASE_PRIVATE_KEY</code><code>STUDENT_SESSION_SECRET</code><code>GOOGLE_DRIVE_FOLDER_ID</code></div><p className="secret-note">ไม่ควร Commit ค่า Secret เหล่านี้ลง GitHub ให้ใส่ใน Vercel Environment Variables เท่านั้น</p></article></section>}
 </StaffShell>
}
function Stat({icon,label,value,sub,color}){return <article className={`staff-stat-card ${color}`}><span className="stat-icon"><UiIcon name={icon} size={24}/></span><div><small>{label}</small><b>{value}</b><em>{sub}</em></div></article>}
function Checklist({done=false,label,sub}){return <div className={`checklist-row ${done?"done":""}`}><span>{done?"✓":"!"}</span><div><b>{label}</b><small>{sub}</small></div></div>}
function Field({label,value,onChange,type="text",placeholder=""}){return <label className="modern-field"><span>{label}</span><input type={type} value={value||""} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/></label>}
function Impact({label,value,warn=false}){return <div className={warn?"warn":""}><span>{label}</span><b>{value}</b></div>}
